DROP TABLE IF EXISTS HITS;

CREATE TABLE IF NOT EXISTS HITS
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       varchar(300),
    uri       varchar(300),
    ip        varchar(100),
    timestamp timestamp,
    CONSTRAINT pk_hits PRIMARY KEY (id)
);